### ISSUE TITLE
Script Error : @mythic_hospital/server/main.lua:85: attempt to call a nil value (field 'removeBank')

### ISSUE THREAD

**Issue by chrissword30** [Quostix/mythic_hospital#11]
I believe we are using ExM the new esx framework from what I heard. When i try to test check-in it takes me to the room but just sits there. I get the attempt to call a nil value console. I have read the readme, and i have seen that i have to implement the framework to work for the billing etc. I am not sure what i am doing incorrectly. Here is my line of code within mythic_hospital/server/main.lua

    	local xPlayer = ESX.GetPlayerFromId(src)
	xPlayer.removeBank(totalBill)
	TriggerClientEvent('esx:showNotification', src, '~w~You Were Billed For ~r~$' .. totalBill .. ' ~w~For Medical Services & Expenses')
	TriggerClientEvent('mythic_hospital:client:FinishServices', src)
end)
Any help would be appreciated. Great Script from what I could tell

**Comment by Quostix** [comment]
ExM is an ESX alternative, not a new version of ESX. With that said, having a quick look through the ExM code, you'll want to change: `xPlayer.removeBank(totalBill)`
To:
`xPlayer.removeAccountMoney('bank', totalBill)`

If that doesn't work, let me know and I'll check the code again once I'm on my computer.
