### ISSUE TITLE
Bleading not removeing !

### ISSUE THREAD

**Issue by subhampro** [Quostix/mythic_hospital#2]
i used every  item still bleeding not removed !!!!!
i used item : 

	('gauze','Gauze', 25),
	('bandage','Bandage', 25),
	('firstaid','First-Aid Kit', 10),
	('medkit','Medkit', 5),
	('vicodin','Vicodin', 5),
	('hydrocodone','Hydrocodone', 5),
	('morphine','Morphine', 5),
        ('adrenaline','Adrenaline', 5)

**Comment by subhampro** [comment]
sorry for weong info not bleding its : spine feels irritate this msg is not going

**Comment by subhampro** [comment]
also bleading and blackout not removing !!

**Comment by Bart-023** [comment]
Same

**Comment by Quostix** [comment]
That's because none of the items were designed to remove limb damage, only treat it.

If you want items to completely remove limb damage you need to add the following in client/items.lua:

`TriggerEvent('mythic_hospital:client:ResetLimbs')`

Add it to the bottom of whatever item you want to remove limb damage.

Example (medkit):

```
function(cancelled)
        if not cancelled then
	    SetEntityHealth(PlayerPedId(), GetEntityMaxHealth(PlayerPedId()))
            TriggerEvent('mythic_hospital:client:ResetLimbs')
        end
```

**Comment by Bart-023** [comment]
I will check it out tomorrow, thanks man!

**Comment by mborisagar** [comment]
same Problem bleeding not removed and get  blackout even after  checked in

Note: I changed the word ESX to XXX in the entire server because of the anti chat

**Comment by mborisagar** [comment]
i get issue  ... its because i clone mythic and 1st at **pillbox** and second in **sandyshore**  so **damage** register in both scripts but when i checked in one hospital so other script damage not removed  
so any way to used check-in both hospital????
