### ISSUE TITLE
Mythic Notify Alert Error

### ISSUE THREAD

**Issue by Afflictionx** [Quostix/mythic_hospital#3]
I do not get any alerts from mythic notify. I just get this error
https://gyazo.com/8dece3322b09e662f40468c39459182b

And when I bandage i get this

https://gyazo.com/d0c3e2e8a9c65ff228e2817e282135fc

**Comment by Quostix** [comment]
One of two possible problems. You either do not have mythic_notify installed or you have an outdated version of mythic_notify.

Solution is to do either of the following:

1) Update your mythic_notify version to the latest
2) Remove mythic_notify notifications from the script completely.

If you do step 2, just replace the notifications with whichever notifications you wish to use.
