### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by ItayKisous** [Quostix/mythic_hospital#7]
I started the script while having all other requirements already activated, went to the PillBox hospital (the coords that are in the client\main.lua) and there was nothing near the check in desk...

**Comment by Quostix** [comment]
You've messed up somewhere then. Did you install it correctly? If you do - check the console for any errors and let me know if there are any,

**Comment by ItayKisous** [comment]
I've put the folder into resources folder, started it in server.cfg after the lines that start mythic_notify, mythic_progbar and the interior but I don't even see the Press to checkin texture

**Comment by ItayKisous** [comment]
nvm, all good the position is just weird
![image](https://user-images.githubusercontent.com/59172678/89938531-4d779180-dc1f-11ea-919a-fad0f175f27a.png)

but one thing, how do you check in while dead?

**Comment by Quostix** [comment]
If the control you have it set to isn't working whilst you are dead, you have another script that is conflicting with it, most probably esx_ambulance that disables controls when one is dead.
