### ISSUE TITLE
REVIVE ISSUE

### ISSUE THREAD

**Issue by PinkHair695** [Quostix/mythic_hospital#9]
if i use ambulance revive the bleeding ot damage is not  disappearing any solution?

**Comment by justinriquier** [comment]
do you fix it?

**Comment by Quostix** [comment]
You'll need to add the events to ambulance function. Find the revive function in your ambulance script and on successful revive, trigger these events:

```
TriggerEvent('mythic_hospital:client:RemoveBleed')
TriggerEvent('mythic_hospital:client:ResetLimbs')
```

**Comment by PinkHair695** [comment]
thanks pugi

**Comment by PinkHair695** [comment]
thanks it work
